version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=root"
      - "DATABASE_PASSWORD=root"
    ports:
      - "3000:3000"
    depends_on:
      - db
